### PR TITLE
Defining global styles and showing Titulo view below Android status bar

### PR DESCRIPTION
**Pull request by ericzucho**
1) Created a global file to store global style variables such as colors. Reference: https://medium.com/the-react-native-log/tips-for-styling-your-react-native-apps-3f61608655eb
2) On Android versions after SDK 20, a view must be added so that the App's first view doesn't show under the status bar (where the clock, signal, battery and other icons are). Reference: https://blog.callstack.io/android-drawer-statusbar-done-right-for-react-native-7e85f01fc099

### CODE REVIEW

**Comment by ericzucho** [comment]
@zamancer Give it a look now, I moved all our existing code into a 'shared' folder and created the 'android' folder that holds this component.

**Comment by zamancer** [comment]
Better on code, not that much folder-wise. I would think the android folder is not needed. Please see the [platform extensions](http://facebook.github.io/react-native/releases/0.49/docs/platform-specific-code.html#platform-specific-extensions) approach. I will try this for iOS early tomorrow and will share findings in a different PR + Slack.

**Comment by ericzucho** [comment]
I've squashed the commits, and tried to edit the commit message, unsuccessfully.

**Comment by ericzucho** [comment]
Can you approve again, so I can merge, @zamancer

**Pull request merged**
